---
- name: Backup Juniper Device Configuration
  hosts: junos_devices
  gather_facts: no
  become: yes

  tasks:
    - name: Save configuration
      Juniper.junos.junos_command:
        commands:
          - "show configuration | display set"
      register: show_config

    - name: Save running configuration to a file
      copy:
        content: "{{ show_config.stdout_lines | join('\n') }}"
        dest: "/path/to/backup/{{ inventory_hostname }}_config_backup.conf"


