---
- name: Backup Juniper Device Configuration
  hosts: Junos-1
  gather_facts: no
  become: yes

  tasks:
    - name: Save configuration
      junos_save:
        destination: "/path/to/backup/{{ inventory_hostname }}_config_backup.conf"
