---
- name: Backup Juniper Device Configuration
  hosts: junos_devices
  gather_facts: no
  become: yes

  tasks:
    - name: Save configuration
      Juniper.junos.junos_save:
        destination: "/path/to/backup/{{ inventory_hostname }}_config_backup.conf"
